version: "3"
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: db
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mlflow
      MYSQL_DATABASE: mlflowdb
      MYSQL_USER: mlflow
      MYSQL_PASSWORD: mlflow
  mlflow:
    image: davidliyutong/mlflow:latest
    restart: unless-stopped
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      MYSQL_DATABASE: mlflowdb
      MYSQL_USER: mlflow
      MYSQL_PASSWORD: mlflow
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MLFLOW_S3_ENDPOINT_URL: http://<your minio host>:9000
      MLFLOW_S3_IGNORE_TLS: "true"
      MLFLOW_S3_BUCKET: mlflow
      AWS_ACCESS_KEY_ID: <your access key>
      AWS_SECRET_ACCESS_KEY: <your secret key>
